name: Nuget Build

on:
  push:
    branches:
      - master

    paths-ignore:
      - '.devcontainer/**'
      - 'docs/**'
      - '**.md'

    tags:
      - v*

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.202'

    - name: Run Unit Tests
      run: dotnet test src/unit-tests --logger:trx     

    - name: Pack and Publish
      run: |
      
        # TODO - merge with dockerCI.yaml

        if [[ "${{ secrets.NUGET_KEY }}" != "" ]];
        then
          dotnet pack src/webvalidate.sln
          dotnet nuget push src/app/nupkg/ --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_KEY }}
        fi
